Feature/add fake data json
kovalenkoiryna15/rsclone pull request #18
Opened 2021-01-08 22:40 UTC by DmitryBogdan90

2021-01-09 08:21 UTC, kovalenkoiryna15 approved these changes

2021-01-09 09:35 UTC, Slnchn commented on src/fake_data.json
> +      "estimatedTime": "59043"
Проекты не привязаны к пользователям.
Приложение будет только для одного пользователя ?

Мб добавить массив `users` с пользователями и поле `user` в объект проекта ?

2021-01-09 13:25 UTC, 375291601334 commented on src/fake_data.json
> +      "estimatedTime": "59043"
я бы даже сказала что вот такая структура лучше подходит:
```js
[
  {
    user: 'Test User',
    tasks: [...],
    projects: [...]
  }
]
```

2021-01-09 15:19 UTC, Slnchn commented on src/fake_data.json
> +      "estimatedTime": "59043"
Хотя я бы наверное не делал такую вложенность.
Лучше просто в каждой таске и в каждом проекте хранить ссылку на юзера.

2021-01-09 21:21 UTC, aplatkouski requested changes
Необходимо разбить commit ``fix: add linebreak rule, fix reset.scss `` на два.
1. ``ci: add linebreak-style=0 to .eslintrc
2. ``fix: apply eslint to  reset.scss`` - если сделаешь rebase, то это изменение пропадёт и тебе только переименовать нужно будет

2021-01-09 21:21 UTC, aplatkouski commented on .eslintrc.js
>      'import/no-unresolved': 'off',
Данные правила противоречат существующей конфигурации eslint + webpack.
Сделай ``rebase``, пожалуйста.

2021-01-09 21:21 UTC, aplatkouski commented on .eslintrc.js
> +    'linebreak-style': 0,
Напомните, данный параметр мы добавляем для тех, кто работает в VSCode под Windows? У не корректный символ переноса строки вставляется?

2021-01-09 21:21 UTC, aplatkouski commented on src/fake_data.json
> +        "100",
``TimeEntries`` - это отдельные объекты. С временем начал, продолжительностью,комментарием и таской к которой они относятся. Т.е. здесь должен быть массив объектов ``TimeEntries``

2021-01-09 21:21 UTC, aplatkouski commented on src/fake_data.json
> +      "description": "Hard task",
Одно из полей лишнее, у нас нет или ``name`` или ``description``

2021-01-09 21:21 UTC, aplatkouski commented on src/fake_data.json
> +      "description": "Prime project",
Данное поле в нашем проекте отсутствует

2021-01-09 21:21 UTC, aplatkouski commented on src/reset.scss
> +  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans',
Если применить stylelint, то он требует перенести каждое значение на отдельную строку.

Необходимо включить stylelint в IDE иначе не избежать ``confilct`` при ``merge``

2021-01-09 21:21 UTC, aplatkouski commented on src/fake_data.json
> +  "tasks": [
В задачах должно быть поле: ``isDone: bool`` или что-то подобное

2021-01-09 21:21 UTC, aplatkouski commented on src/fake_data.json
> +  "projects": [
У ``project`` должно быть поле: ``defaultView`` содержащее или ``"list"`` или ``"board"``

2021-01-09 21:21 UTC, aplatkouski commented on src/fake_data.json
> +{
файл необходимо переместить в ./src/assets/data/

Доступ к файлу из кода с помощью ``alias``
```
import fakeData from 'Data/fake_data.json';
```

2021-01-12 22:25 UTC, aplatkouski approved these changes

2021-01-12 22:25 UTC, merged