Feature/modal component
kovalenkoiryna15/rsclone pull request #19
Opened 2021-01-09 12:25 UTC by kovalenkoiryna15

2021-01-09 13:29 UTC, 375291601334 commented on src/components/ModalWindow/ModalWindow.tsx
> +};
лучше использовать что-то одно - или propTypes, или Typescript. Мы вроде решили, что используем Typescript, поэтому propTypes излишний.

2021-01-09 13:35 UTC, 375291601334 commented
Пропиши ещё пожалуйста слили

2021-01-09 14:22 UTC, kovalenkoiryna15 commented
> Пропиши ещё пожалуйста слили

Настя, возник вопрос, можно ли сделать модальное окно только используя компонент bootstrap [Modal](https://getbootstrap.com/docs/4.0/components/modal/) и не создавая портал ?

2021-01-09 21:25 UTC, aplatkouski requested changes
Необходимо выполнить ``rebase`` текущей ветки на последнюю версию ``develop``. Т.к. часть предложенных изменение уже существует в ``develop``

2021-01-11 13:08 UTC, kovalenkoiryna15 commented
Было принято решение использовать компонент bootstrap Modal.

2021-01-11 13:08 UTC, closed without merging

2021-01-11 16:34 UTC, 375291601334 commented on src/store/store.ts
> +ReturnType,
отступы не надо удалять