feature/authorization_modal
kovalenkoiryna15/rsclone pull request #27
Opened 2021-01-22 21:41 UTC by kovalenkoiryna15

2021-01-27 20:43 UTC, Slnchn commented on src/components/LoginModal/RegisterForm/RegisterForm.tsx
> +        id: Date.now(),
Я обычно использую [этот модуль](https://www.npmjs.com/package/uuid), когда нужно создать id.
Но здесь `Date.now()` вроде норм.

2021-01-27 20:43 UTC, Slnchn commented on src/components/LoginModal/RegisterForm/RegisterForm.tsx
> +  const emailRef = useRef<HTMLInputElement>(null);
Если я правильно понимаю, ты делаешь реф на инпут и потом смотришь `value` по этому рефу.
Мб проще сделать контролируемый компонент (через `state`) ?

```jsx
function Form() {
  const [email, setEmail] = useState('');
  
  function handleChange(event) {
    const { target: { value } } = event;
    setEmail(value);
  }
  
  return ( 
    <form>
      <input type="text" value={email} onChange={handleChange} />
    </form>
  );
}
```

Тогда при сохранении юзера проверка будет проще:

```js
if (email && password)

// вместо

if (emailRef && emailRef.current && passwordRef && passwordRef.current)

```

2021-01-27 20:43 UTC, Slnchn commented on src/components/ProjectForm/ProjectForm.tsx
> +      }
Можно упростить

![image](https://user-images.githubusercontent.com/40535982/106049920-bda7a000-60f7-11eb-8c2e-75920bfbee34.png)


```js
const newProject = {
  id = `${Date.now()}`, title, deadline, estimatedTime, color,
};
```
Если `id === undefined`, в него засетается `${Date.now()}`.
Если `id !== undefined`, его значение останется.

2021-01-27 22:53 UTC, aplatkouski requested changes

2021-01-27 22:53 UTC, aplatkouski commented on src/store/user/user-reducers.ts
> +import * as MyModels from 'Store/types';
Думаю файл стоит переименовать в ``reducers.ts``, как это сделано у остальных

2021-01-27 22:53 UTC, aplatkouski commented on src/store/user/user-reducers.ts
> +  loggingIn: false,
Не настаиваю, но я бы заменил на ``isLogged`` или ``isRegistered``

2021-01-27 22:53 UTC, aplatkouski commented on src/store/user/user-reducers.ts
> +  alertMessage: null,
Видел и ранее у тебя в коде такие переменные состояния, но не понимаю зачем они нужны и как используются.
Для чего мы их храним?

2021-01-27 22:53 UTC, aplatkouski commented on src/store/user/user-types.ts
> +  password: string | number;
```
password: string;
```
числовых данных там не будет. А все числа интерпетируются, как строка

2021-01-27 22:53 UTC, aplatkouski commented on src/store/user/user-types.ts
> +  alertMessage?: string | null;
По-моему если ``?``, то `` | null`` можно не добавлять. Это предполагается

2021-01-27 22:53 UTC, aplatkouski commented on src/components/LoginModal/LoginForm/LoginForm.tsx
> +  const [validated, setValidated] = React.useState<boolean>(false);
Необходимо реализовать их с помощью ``redux``

2021-01-27 22:53 UTC, aplatkouski commented on src/components/LoginModal/LoginModal.tsx
> +const LoginModal = (props: TLoginModalProps): JSX.Element => {
Думаю нет смысла вводить доп. переменную ``props``:
```ts
 const LoginModal = ( { isVisible }: TLoginModalProps): JSX.Element => {
// ...
  const { isVisible } = props;  // <-- эту строку можно будет удалить
// ...
```

2021-01-27 22:53 UTC, aplatkouski commented on src/components/LoginModal/LoginModal.scss
> +.login-modal {
Возможно (?) стоит приссмотреться к [Bootstrap | Utilities](https://getbootstrap.com/docs/5.0/utilities/)?

2021-01-27 22:53 UTC, aplatkouski commented on src/components/LoginModal/RegisterForm/RegisterForm.tsx
> +  const [validated, setValidated] = React.useState<boolean>(false);
Реализовать с помощью ``redux``

2021-01-27 22:53 UTC, aplatkouski commented on src/entities/user-entities.ts
> +type ID = string | number;
Чтобы у всех entities ID был одного типа, лучше его импортировать из одного места:

```ts
import * as Types from 'Entities/types';

export interface IUser {
  id: Types.ID;
// ...
```

2021-01-27 22:53 UTC, aplatkouski commented on src/components/LoginModal/LoginForm/LoginForm.tsx
> +      dispatch(login(user));
Я полагаю, что вводить переменную для одноразового ипользования излишне. Думаю здесь будет лучше
```ts
dispatch(login({ username, password }));
```

2021-01-27 22:53 UTC, aplatkouski commented on src/store/user/user-reducers.ts
> +export const initialUserState: IUserState = {
Предположу, что ты добавила ``export`` и переименовала, чтобы не было конфликтов с другими ``initialState`` при импорте?! Возможно лучше решить это, добавиви ``import initialState as initialUserState from 'Store/user/reducers'``?

2021-01-27 22:53 UTC, aplatkouski commented on src/components/LoginModal/RegisterForm/RegisterForm.tsx
>          />
У тебя данный элемент используетя с абсолютно одинаковыми параметрами в двух местах. И ты каждый раз редактируешь два файла. 
Возможно стоит вынести данный элемент в отдельный компонент с заданными параметрами и экспортировать его? Тоже относитя и к форме пароля

2021-01-27 22:53 UTC, aplatkouski commented on src/components/ProjectForm/ProjectForm.tsx
> +  deadline?: string;
Ох, это мне не нравится. В системе храним ``Date``, при сохрании в БД конвертируем в строку (если она date не поддериживает) и из строки в Date после загрузки из БД

Пример кода (из **другого проекта**): ``src/store/task/actions.ts``
```ts
// eslint-disable-next-line @typescript-eslint/no-unsafe-return
const parseTask = (data: FirebaseData<ITask>) => Object.entries(data)
  .map(([
    key, {
      deadline,
      timeEntries,
      ...taskRest
    },
  ]) => ({
    id: key,
    deadline: deadline && new Date(deadline),
    timeEntries: timeEntries.map(
      ({
        startDate,
        ...timeEntryRest
      }: ITimeEntry) => ({
        startDate: new Date(startDate),
        ...timeEntryRest,
      }),
    ),
    ...taskRest,
  }));

export const getTasks = (): Promise<Array<ITask>> => axios
  .get<FirebaseData<ITask>>(`${url}/tasks.json`, { timeout: AXIOS_TIMEOUT })
  .then((response) => {
    if (response.status === 200 && response.data) {
      return parseTask(response.data);
    }
    return [];
  });
```

2021-01-27 23:17 UTC, aplatkouski commented on src/components/LoginModal/RegisterForm/RegisterForm.tsx
> +        id: Date.now(),
Т.к. эти данные должны быть сохранены в БД, то нет необходимости самому создавать ``id``, он будет получен в ответе на команду ``post``. 
Чтобый пройти проверку TypeScript, используй конструкцию
```ts
const newUser: Omit<IUser, 'id'> = {
// ...
}
```
Пример работающего кода:
```ts

export const addTask = (title: string): MyModels.AsyncDispatch<ITaskState, any> => async (
  dispatch,
) => {
  dispatch(showLoader());
  const task: Omit<ITask, 'id'> = {
    title,
    timeEntries: [],
    isCompleted: false,
  };
  const { id } = await postTask(task);
  dispatch({
    type: ADD_TASK,
    payload: {
      ...task,
      id,
    },
  });
  dispatch(hideLoader());
};
```

2021-01-27 23:43 UTC, aplatkouski commented on src/components/LoginModal/RegisterForm/RegisterForm.tsx
> +  const emailRef = useRef<HTMLInputElement>(null);
Я бы вынес input в отдельный компонент ``emailInput`` (или ``inputEmail``). По аналогии можно сделать с input-ом для password.

Т.к. мы используем **redux**, то состояние ``email`` лучше не использовать локальным (используя ``useState``)

Возможные вариант:
### ``src/components/EmailInput/EmailInput.tsx``
```ts
import * as React from 'react';

const EmailInput = ({
  email, onChange, onKeyPress
}) => (
  <form onSubmit={submitHandler}>
      <input
        placeholder="E-mail"
        aria-describedby="button-add-email"
        type="text"
        tabIndex={0}
        value={email}
        onChange={onChange}
        onKeyPress={onKeyPress}
      />
  </form>
);


export default EmailInput;

```

### ``store/email-input/reducers.ts``
```ts

import { IEmailInputState,  IEmailInput} from './action-types;
import { SET_EMAIL } from './action-constans';

const initialState: IEmailInput = {
  email: '',
};

const handlers: MyModels.IHandlers<IEmailInputState, any> = {
  [SET_EMAIL]: (state, { payload: email }: MyModels.IAction<IEmailInput>) => ({
    ...state,
    email,
  }),
  DEFAULT: (state) => state,
};

const emailInputReducer = (state = initialState, action) => {
  const handle = handlers[action.type] || handlers.DEFAULT;
  return handle(state, action);
};

export default emailInputReducer;

```

### ``src/store/email-input/actions.ts``
```ts

import { SET_EMAIL } from './action-constants';

export const setEmail = (email) => ({ type: SET_EMAIL, payload: email });
 
export const onChange = (event) => ({ type: SET_EMAIL, payload: event.target.value });

export const onKeyPress = (event) => (dispatch) => {
  if (event.key === 'Enter') {
    // ...
   // Если это последний элемент на форме, можно инициировать другие связаныне действия,
  // предварительно их импортировав
  }
};
```

### ``src/store/reducers.ts``
```ts
// ...

import emailInputReducer from 'Store/email-input/reducers';
//...
const rootReducer = combineReducers({
  // ...
  emailInput: emailInputReducer,
});

export default rootReducer;
```

### Дополнительно
* добавить типизацию в ```actions.ts``
* добавить ``action-constants.ts``, ``action-types.ts``

2021-01-28 07:07 UTC, Slnchn commented on src/components/LoginModal/RegisterForm/RegisterForm.tsx
> +  const [validated, setValidated] = React.useState<boolean>(false);
Не вижу преимуществ хранить данные формы в редаксе вместо локального стейта

В редакс-стор обычно выносятся:
- данные, используемые между компонентами на разных уровнях
- какой-то асинхронный флоу

На ввод каждого символа в каждый инпут, привязанный к стору, будет диспатчится action
Этот action будет пробегать по всем редьюсерам 
То есть много лишних проверок редакса
Даже если редакс-стор будет сильно большой, на современных компьютерах это не будет заметно, но в основном сейчас сайты открываются на мобильниках - нужно помнить о перфомансе

Я к тому, что если есть редакс, это не значит что нельзя использовать локальные стейты
Что-то общее выносим в редакс
Что-то маленькое и локальное храним в локальном стейте компонента

Так что не вижу проблемы использовать локальный стейт для формы

Но вообще смотрите сами, как вам удобнее по проекту)

2021-01-28 07:11 UTC, Slnchn commented on src/store/user/user-types.ts
> +  alertMessage?: string | null;
[Разбор похожей ситуации](https://stackoverflow.com/a/57243788)

2021-01-30 11:43 UTC, kovalenkoiryna15 commented on src/store/user/user-reducers.ts
> +  loggingIn: false,
чтобы не выбирать одно из двух, я назову isAuthorized

2021-01-30 11:47 UTC, kovalenkoiryna15 commented on src/components/LoginModal/RegisterForm/RegisterForm.tsx
> +  const emailRef = useRef<HTMLInputElement>(null);
Хм.. я бы не записывала `email` в redux  `state` на каждый `onChange`, у нас нет состояний который бы зависели от значения `email`, поэтому я бы один раз записала после сабмита и валидации

2021-01-30 13:14 UTC, kovalenkoiryna15 commented on src/store/user/user-reducers.ts
> +  alertMessage: null,
`loggingIn` состояние я использую чтобы показать/убрать модальное окно

2021-01-30 14:06 UTC, kovalenkoiryna15 commented on src/components/ProjectForm/ProjectForm.tsx
> +  deadline?: string;
@aplatkouski  а для чего мы игнорим `id` в `FirebaseData`?

2021-01-30 14:17 UTC, kovalenkoiryna15 commented on src/components/ProjectForm/ProjectForm.tsx
> +  deadline?: string;
можно ещё вот так парсить
```
const parseProject = (data: IProject): IProject => ({
  ...data,
  deadline: data.deadline && new Date(data.deadline),
});
```

2021-01-30 15:40 UTC, aplatkouski commented on src/store/user/user-reducers.ts
> +  alertMessage: null,
``alertMessage`` - у меня вот эта поле вызвало вопросы.

2021-01-30 15:50 UTC, kovalenkoiryna15 commented on src/components/ProjectForm/ProjectForm.tsx
> +  deadline?: string;
я бы не хранила объект `Date`
`input type="date"` не принимает этот тип

> Type 'string | Date | undefined' is not assignable to type 'string | number | string[] | undefined'.
>   Type 'Date' is not assignable to type 'string | number | string[] | undefined'.

2021-01-30 15:51 UTC, kovalenkoiryna15 commented on src/components/ProjectForm/ProjectForm.tsx
> +  deadline?: string;
с этим много доп операций придется делать, но попробую прислушаться и подправить под объект Date

2021-01-30 16:31 UTC, aplatkouski commented on src/components/LoginModal/RegisterForm/RegisterForm.tsx
> +  const [validated, setValidated] = React.useState<boolean>(false);
@Slnchn спасибо за обратную связь.

К сожаленею, у меня минимальный опыт работы с ``redux``, и основываясь на нём я полагал, что функциональные (stateless) компоненты должны быть минимальны, как это возможно. В итоге я пришёл к такой схеме ``tree ./src``:
```
.
├── App.scss
├── App.tsx
├── assets/
├── components
│   └── TaskItem
│          ├── TaskItem.tsx  # минимально необходимый код, чтобы вернуть JSX.Element
│          │                              # самое сложное что здесь есть, это проверки, какие классы
│          │                              # должны быть у элементов, и какие элементы отображать
│          │                              # вся логика (функции) и данные (redux) попадают в элемент
│          │                              # в виде props
│          └── TaskItemContainer.tsx  # redux обёртка вокруг TaskItem. Импортирует нужные методы и состояния 
│                                            # и передаёт в TaskItem с помощью:
│                                            # export default connect(mapStateToProps, mapDispatchToProps)(TaskItem);
│                                            # если решили заменить redux на graphql или что-то другое, меняем этот файл
│                                            # TaskItem компоннет НЕ трогаем
├── entities
│   └── task-entities.ts      # описание интерфейса ITask, который должен быть передан в TaskItem в виде props
├── favicon.ico
├── index.scss
├── index.tsx
├── reset.scss
├── store
│   ├── reducers.ts  # используя ``combineReducers`` объеденяет reducers всех компоннетов в один
│   ├── store.ts        # создаёт глобальный store с пощьмю ``createStore``, обогащая его middleware:
│   │                            #   thunk, logger
│   ├── task             # самое интересное
│   │   ├── action-constants.ts  # "ключи" reducers (используется в actions и reducers)
│   │   ├── action-types.ts   # описание интерфейса ITaskState, используется в actions и reducers
│   │   ├── actions.ts           # здесь и только здесь описывается логика, приводящая к изменению состояния
│   │   └── reducers.ts        # изменения состояния. Функция должно быть идеальной (зависить только от
│   │                                        #   входящих параметров).
│   └── types.d.ts
└── template.ejs
```

Основания идея, отделить Отображение (компонент) от подключенияя redux (см. *Container.tsx), от логики (см. store/*/actions.ts) и от изменения состояния (см. store/*/reducers.ts).

> Этот action будет пробегать по всем редьюсерам

Если вопрос о ``reducers.ts``, то доступ к значению поля объекта это O(1). 

Меня самого "пугает" раздробленность приложения, но красивее я пока не придумал.

### Вопрос:

Возможно есть ссылка или свои законспектированные наработки по best-practices, как создавать react-redux приложение? В интеренте, их много, слишком много и у меня не хватает знаний, чтобы выбрать самому.

2021-01-30 16:42 UTC, aplatkouski commented on src/components/ProjectForm/ProjectForm.tsx
> +  deadline?: string;
@kovalenkoiryna15 

> @aplatkouski а для чего мы игнорим `id` в `FirebaseData`?

``id`` нам вернёт firebase в ответе. Т.е. в БД ты должна отправить объекта **без** поля id.

> можно ещё вот так парсить
> 
> ```
> const parseProject = (data: IProject): IProject => ({
>   ...data,
>   deadline: data.deadline && new Date(data.deadline),
> });
> ```

``FirebaseData`` - это объект, у которого **каждое** поле (key) соответсвует id таска, а значение (value) представляет из себя объект со всеми другими полям таска (кроме id). Т.о. у ``data`` нет поля ``deadline``. Т.о. если у нас 10 task, то у нас 10ть полей в объекте. Поэтому мы превращаем его в Array пар [key, value], а потом "разворачиваем" value, чтобы преобразовать строкову данные в нужным нам тип (например строку в дату)

см.
```ts
export interface FirebaseData<T> {
  [key: string]: Omit<T, 'id'>
}
```

2021-01-30 17:43 UTC, Slnchn commented on src/components/LoginModal/RegisterForm/RegisterForm.tsx
> +  const [validated, setValidated] = React.useState<boolean>(false);
Спойлер: наработок нет, гайдов нет

### 1. Касательно пробегания по всем редьюсерам
```js
module.exports = {
  /* мой упрощенный combineReducers.
     вызывается после каждого dispatch */
  combineReducers(reducersMap) {
    return (state, action) => {
      // сюда будем сохранять пересчитанные стейты
      const nextState = {};

      /* проходимся по всем редьюсерам, которые замапили при создании store,
         и пересчитываем стейты каждого редьюсера. */
      Object.keys(reducersMap).forEach((reducerKey) => {
        /* в каждый редьюсер передаем его стейт и экшн, который только что задиспатчили. 
           то есть на каждый dispatch вызываются все редьюсеры и пересчитывается весь стейт. 
           (редьюсеры, к которым не относится action, возвращают свой default case).
           а на onChange инпута этот пересчет выполняется сильно часто, мне это не понравилось.
           + доступ к полю объекта редьюсера будет количество_редьюсеров * O(1)
           + я не знаю, будет ли O(1), если не находим значение в мапе вашего редьюсера => default case. */
        nextState[reducerKey] = reducersMap[reducerKey](state[reducerKey], action);
      });

      // возвращаем пересчитанный стейт
      return nextState;
    };
  },
};
```

[Настоящий combineReducers](https://github.com/reduxjs/redux/blob/master/src/combineReducers.ts).

### 2.

> К сожаленею, у меня минимальный опыт работы с redux, и основываясь на нём я полагал, что функциональные (stateless) компоненты должны быть минимальны, как это возможно.

Я воспринимаю редакс, как глобальную переменную, и выношу туда значения, которые могут используются между компонетами.

Кроме того, через `redux-saga` редаксом удобно делать сложные флоу (в том числе асинхронные).
Например:
1. Показать спиннер;
2. Сделать запрос на создание todo;
3. Когда todo создастся, сделать запрос на все todo;
4. Когда все todo придут, сетнуть их в redux;
5. (Если ошибка, убрать спиннер и показать тост с ошибкой);
5. Убрать спиннер;

Ну а если данные нужны только в компоненте, то **в чем конкретная проблема использовать локальный стейт ?**

### 3.

> Основания идея, отделить Отображение (компонент) от подключенияя redux (см. Container.tsx), от логики (см. store//actions.ts) и от изменения состояния (см. store/*/reducers.ts).

Отделять логику от представления правильно, согласен.

Не согласен, что логика должна быть в actions.
Я воспринимаю actions, как events с добавленным payload у паттерна Observer.
Ну и поэтому логику в них не храню.

Я понимаю, что вы используете `redux-thunk`, и в этом случае асинхронные приколы дейсвительно переносятся в actions, но по-хорошему логики в actions быть не должно.
Вместо `redux-thunk` я использую `redux-saga` (саги сложнее применять, но код становится проще).

Кроме того, я всегда делаю reducers через switch, а не через map.
Не видел редьюсеров через map вообще, но проблем с этим не вижу.

### 4. best-practices

Когда учил реакт с редаксом сам ничего не нашел.
Писал маленькие проекты и постепенно получал удобный для себя шаблон react + redux.
Профессионального опыта с реактом нет, поэтому не уверен в адекватности своих шаблонов.

2021-01-30 18:28 UTC, kovalenkoiryna15 commented on src/components/ProjectForm/ProjectForm.tsx
> +  deadline?: string;
@aplatkouski  кстати, я вот дошла до момента [добавления проектов в БД](https://firebase.google.com/docs/database/web/read-and-write) и как я понимаю мы можем свой `id` использовать
```
function writeUserData(userId, name, email, imageUrl) {
  firebase.database().ref('users/' + userId).set({
    username: name,
    email: email,
    profile_picture : imageUrl
  });
}
```

2021-01-30 18:55 UTC, kovalenkoiryna15 commented on src/components/ProjectForm/ProjectForm.tsx
> +  deadline?: string;
только для проектов тогда будет `${key}/projects/` 
 ```
const key = crypto.createHash('sha256').update(`${username}${password}`).digest('hex');
console.log(key);
```

2021-01-30 19:01 UTC, kovalenkoiryna15 commented on src/components/ProjectForm/ProjectForm.tsx
> +  deadline?: string;
ещё тут есть вопросы, username поле я удалила за ненадобностью при авторизации, а password в стейте хранить тоже не имеет смысла, поэтому может использовать для генерации key модуль, который Саша предложил?

2021-01-30 19:03 UTC, kovalenkoiryna15 commented on src/components/ProjectForm/ProjectForm.tsx
> +  deadline?: string;
или email криптографировать

2021-01-30 19:06 UTC, aplatkouski commented on src/components/ProjectForm/ProjectForm.tsx
> +  deadline?: string;
> @aplatkouski кстати, я вот дошла до момента [добавления проектов в БД](https://firebase.google.com/docs/database/web/read-and-write) и как я понимаю мы можем свой `id` использовать
> 
> ```
> function writeUserData(userId, name, email, imageUrl) {
>   firebase.database().ref('users/' + userId).set({
>     username: name,
>     email: email,
>     profile_picture : imageUrl
>   });
> }
> ```

По-моему, там выше по коду, сначала ты создаёшь **пустой** объект, получаешь ID, а после заносишь необходимые данные.

2021-01-30 19:12 UTC, kovalenkoiryna15 commented on src/components/ProjectForm/ProjectForm.tsx
> +  deadline?: string;
там авторизация, это немного другое, мне так кажется... там я получаю tokenId

2021-01-30 19:20 UTC, Slnchn commented on src/components/ProjectForm/ProjectForm.tsx
> +  deadline?: string;
Для шифрования пароля в БД я использовал [bcrypt](https://www.npmjs.com/package/bcryptjs).
Но я его использовал только в Node, не знаю будет ли работать в браузере (на npmjs пишут, что можно).

Но вы лучше сделайте больше use cases, за

2021-01-31 14:33 UTC, kovalenkoiryna15 commented on src/components/ProjectForm/ProjectForm.tsx
> +  deadline?: string;
по итогу при регистрации получаю uid (user id), который используется для создания ключа в DB, по этому ключу создается объект с ключом projects
в projects сохраняются проекты по ключу, который равен id проекта
вот пример DB, в которой зарегистрированы 3 юзера
![image](https://user-images.githubusercontent.com/52598991/106387365-79174f80-63ea-11eb-97e5-2dbd2dcc5b4e.png)

2021-01-31 14:38 UTC, kovalenkoiryna15 commented on src/components/ProjectForm/ProjectForm.tsx
> +  deadline?: string;
![image](https://user-images.githubusercontent.com/52598991/106387512-25f1cc80-63eb-11eb-907f-17ca0b8a1f20.png)

2021-01-31 14:39 UTC, kovalenkoiryna15 commented on src/components/ProjectForm/ProjectForm.tsx
> +  deadline?: string;
user id сохраняется в стейте сразу при регистрации

2021-02-01 12:00 UTC, aplatkouski approved these changes

2021-02-01 12:01 UTC, merged